name: Build and deploy to k8s
on:
  push:
    branches:
      - master
      - main
jobs:
  # Build Channel Manager Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/travelaps/generic_nodejs:v${{ github.run_number }}
            ghcr.io/travelaps/generic_nodejs:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
